### ISSUE TITLE
training a single model for all question types

### ISSUE THREAD

**Issue by ardakdemir** [dmis-lab/bioasq-biobert#2]
Dear authors,

I got confused about the training/prediction procedures for different question types.
Specifically, I would be glad if you can clarify whether it is possible to train a single model for all question types at once. After reading the paper and going over the repository, it seemed to me that the we have to train the model for each question type separately. 

Kind regards

Arda

**Comment by wonjininfo** [comment]
Hello Arda,
Thank you for your interests in our work!
No, you need to train the model for a specific task. 

Our model shares identical structures (when we only consider trainable parameters) for factoid questions and list questions. However, it doesn't mean that we used identical parameters for multiple question types. 

Therefore, let's say if you wish to get optimal performances for 1) factoid questions and 2) list questions, then you need to train the model twice and should use two checkpoints for inferencing. 

ps) We believe using factoid model for inferencing list questions would output quite a comparable performance, but there will be some performance decrease. (Haven't checked)

Thanks!
Wonjin

**Comment by ardakdemir** [comment]
Thanks a lot for your reply!
