### ISSUE TITLE
Is there a way to decipher the factoid output?

### ISSUE THREAD

**Issue by tonyreina** [dmis-lab/bioasq-biobert#3]
Thanks for such a great repository. I was able to quickly follow the directions and get a predictions for the factoid task. I'm new to the BioASQ dataset and am unsure of how to interpret the prediction file. This is what I see:

```
head /tmp/factoid_output/predictions.json
{
    "5a735cdc3b9d13c708000004_000": "2-3",
    "5a777ab9faa1ab7d2e00000a_000": "insomnia",
    "5a777ab9faa1ab7d2e00000a_001": "Suvorexant is a dual orexin receptor agonist and is currently approved for the treatment of insomnia",
    "5a777ab9faa1ab7d2e00000a_002": "insomnia",
    "5a777ab9faa1ab7d2e00000a_003": "insomnia",
    "5a6a3464b750ff4455000026_000": "MARS",
    "5a74e9ad0384be955100000a_000": "selective estrogen receptor modulators",
    "5a74e9ad0384be955100000a_001": "selective estrogen receptor modulator",
    "5a74e9ad0384be955100000a_002": "selective estrogen receptor modulators",
```

Does the "5a777ab9faa1ab7d2e00000a_002" refer to a question somewhere in the original BioASQ corpus? Is there a way to map this back to the text?

Thanks!

**Comment by tonyreina** [comment]
Nevermind. I figured out that the prediction file was being passed and that the alphanumeric was the question id. So to get the original text I did:

cat data-release/BioASQ-6b/test/Full-Abstract/BioASQ-test-factoid-6b-3.json | grep -A5  5a735cdc3b9d13c708000004_000

**Comment by wonjininfo** [comment]
Hi Tony,
Thanks a lot for your attention to our work. 
BioASQ dataset is composed of "question" and "context" sets. 
(Context means corresponding passage. It's usually sentences or abstract from biomedical papers.)
Each set contains one question and **multiple** contexts. 

We made id by combining _question id_ and _index of each context_ in question and context sets.
For example, question "5a777ab9faa1ab7d2e00000a" has four corresponding contexts. 
We can interpret "5a777ab9faa1ab7d2e00000a_002" ("insomnia") as the prediction of question "5a777ab9faa1ab7d2e00000a" based on the third (002) context. 

Thanks!
Wonjin

**Comment by wonjininfo** [comment]
ps) So you can think "5a777ab9faa1ab7d2e00000a_002" as a unique key for a _context_. 
For factoid questions, our model predicts a single prediction for a _context_.
Therefore a question may have multiple answers. 
We choose the best answer among them for a question.
